### ISSUE TITLE
does not compile on Fedora 23

### ISSUE THREAD

**Issue by silberzwiebel** [UCL-CATL/gcsvedit#11]
Hi there,

I tried to compile gcsvedit on Fedora 23, but unfortunately it didn't work.

This is the command I used:

```
./autogen.sh
```

and this is the output with error message I got:

```
*** WARNING: I am going to run `configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** `./autogen.sh\' command line.

autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force --warnings=no-portability --install -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force --warnings=no-portability
configure.ac:44: error: possibly undefined macro: PKG_CHECK_MODULES
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

It might be that I just miss some packages needed for compilation, as I never compiled a GTK program by myself. Which ones do I need?

Thanks,
silberzwiebel

**Comment by swilmet** [comment]
I'm using Fedora 22 at work and Fedora 23 on my personal computer, and it works fine. But I use Jhbuild:
https://wiki.gnome.org/Projects/Jhbuild

Currently gCSVedit depends on unstable releases of GtkSourceView and GTK+. A stable version will be available in Fedora 24. With Jhbuild, the GNOME dependencies are compiled from Git, so it works.

For Linux systems, I plan to provide an xdg-app:
https://wiki.gnome.org/Projects/SandboxedApps
which will be the preferred method on Fedora for desktop applications.

Note that gCSVedit is currently under development, although the master branch should be quite usable and useful already.

**Comment by swilmet** [comment]
For the specific problem you are encountering, install autoconf-archive and launch:
# yum-builddep gtksourceview3

But without Jhbuild, you won't have a recent enough version of GtkSourceView.
You can try the gcsvedit-0-0-1 branch though that should work on Fedora 23 without Jhbuild. But it lacks some important work done on the master branch.

**Comment by swilmet** [comment]
"Fixed":
https://github.com/UCL-CATL/gcsvedit/commit/5deedb506384a45d6737fcd147505ea7f7aad230

gCSVedit is not yet meant for mass adoption, it's still under development.
